# Generated by Django 4.2.5 on 2023-09-23 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TodoList',
            fields=[
                ('tl_id', models.IntegerField(primary_key=True, serialize=False)),
                ('tl_title', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('ta_id', models.IntegerField(primary_key=True, serialize=False)),
                ('ta_title', models.CharField(max_length=256)),
                ('ta_description', models.TextField(blank=True, null=True)),
                ('ta_check', models.BooleanField(default=False)),
                ('ta_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OneTask.todolist')),
            ],
        ),
    ]
